# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='view_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.Category'),
        ),
    ]
